services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data:rw
    env_file:
      - .env

volumes:
  db: